# 1. Datasource config
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
spring.datasource.url: jdbc:mysql://localhost:3306/book_my_show
spring.datasource.username: root
spring.datasource.password: hariom

## 2. Hibernate config
spring.jpa.show-sql: true
#spring.jpa.hibernate.ddl-auto: create-drop
spring.jpa.hibernate.ddl-auto: create
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

app-config:
  simpleKey: "value"
  timeout : 5s     # working


